Ce glider
oceanobservatories/asset-management pull request #797
Opened 2021-01-22 02:41 UTC by s-pearce

adds recent CE glider deployments and recoveries and metadata.

2021-01-23 18:16 UTC, cwingard submitted a review, later dismissed

2021-01-23 18:30 UTC, cwingard requested changes
@s-pearce You need to make 2 more before we can merge. The nose tests failed (see the Travis build results at https://travis-ci.org/github/oceanobservatories/asset-management/builds/755633228) for two tests. You need to add glider 871 to the vocab/vocab.csv, and ADCPA-M S/N 55731 needs to be added to the bulk/sensor_bulk_load-AssetRecord.csv. You have a calibration file for it, but if it does not exist in the bulk load, the tests fails.

2021-01-24 17:15 UTC, cwingard commented
@s-pearce The error is in the two adcp cal files for `calibration/ADCPAM/CGINS-ADCPAM-55731__20180807.csv` and `calibration/ADCPAM/CGINS-ADCPAM-73107__20190831.csv`. In both cases, you have the serial number in the cal files as `672777`.

2021-01-24 20:48 UTC, s-pearce commented
I did not know I needed to add the new glider to the vocab file, sorry about that.  
Also, I had added the ADCP to the bulk_sensor file, but I had forgotten to update the serial number in the contents of the new csv file I created for it.

2021-01-25 02:48 UTC, cwingard approved these changes

2021-01-25 02:48 UTC, merged