adds recent CE glider ops and updates G3 reference designators
oceanobservatories/asset-management pull request #831
Opened 2021-06-22 23:27 UTC by s-pearce

@cwingard can you review my additions of glider deployments 871-00002, 311-00012, and 383-00011 and recoveries 326-00009 and 386-00013?

@rtravis-whoi I included you for review because I updated our G3 to have the new style of reference designator including for a deployment that occurred before the style change (871-00001).  Since you recently updated ref des's for your G3's I thought it would be good to have you review.  Feel free to pass this review on to whoever edited the WHOI G3's if it was not you.
Thanks, 
Stuart

2021-06-22 23:28 UTC, s-pearce commented
Also, I passed the nosetests even after the vocab changes and also added our newest G3 917 into the vocab, though it has not yet been deployed.

2021-06-24 14:24 UTC, rtravis-whoi approved these changes
The G3 glider RefDes updates look good to me.  I added specific 'looks good' comments to the portions I reviewed.

2021-06-24 14:24 UTC, rtravis-whoi commented on deployment/CE05MOAS-GL871_Deploy.csv
> +EK20210120,,SKQ202104S,S.Pearce,CE05MOAS-G0871-05-CTDGVM000,1,1,2021-01-21T18:05:00,2021-03-24T22:10:00,CGVCE-05MOAS-00000,CGVEH-GLDRCE-00871,CGINS-CTDGVM-09658,44.632,-124.305,,1000,1000,,,
update to deployment 00001 G3 RefDes looks good

2021-06-24 14:24 UTC, rtravis-whoi commented on vocab/vocab.csv
> +CE05MOAS-G0871-05-CTDGVM000,Coastal Endurance,Mobile Assets,Coastal Glider 871,CTD,Sea-Bird,SBE Glider Payload CTD (GP-CTD),0,1000
G3 RefDes updates look correct to me

2021-06-24 14:24 UTC, rtravis-whoi commented on vocab/vocab.csv
> +CE05MOAS-G0917-05-CTDGVM000,Coastal Endurance,Mobile Assets,Coastal Glider 917,CTD,Sea-Bird,SBE Glider Payload CTD (GP-CTD),0,1000
New G3 glider RefDes look good to me.

2021-06-24 14:59 UTC, cwingard requested changes
The deployment/CE05MOAS-GL871_Deploy.csv file should be renamed to deployment/CE05MOAS-G0871_Deploy.csv

2021-06-24 16:16 UTC, s-pearce commented
@cwingard Good catch.  I've rename the file and pushed it to the pull request.

2021-06-24 16:44 UTC, cwingard approved these changes

2021-06-24 16:44 UTC, merged