update AM with D00025 CE02 and finalized D00024
oceanobservatories/asset-management pull request #919
Opened 2022-05-27 18:05 UTC by lstoltz

I will send file checks in an email.

2022-05-27 21:32 UTC, cwingard requested changes
Need to update the cruise end time. Also, need to send me the nutnr cal file.

2022-05-27 21:32 UTC, cwingard commented on cruise/CruiseInformation.csv
> +EK20220526,Elakha,2022-05-26T16:02:00,2022-05-26T19:04:00,Endurance CE02SHSP turn
You have the launch time of the CSPP as the end time of the cruise. Time should be 22:22 from the config sheet.

2022-05-27 21:41 UTC, cwingard approved these changes

2022-05-31 16:03 UTC, desiderr commented
Verified serial numbers from pre-deployment test files, except for the ctd and velpt. Everything else appears to be in order except for a discrepancy in deployment latitude. The cruise report reports 44 degrees, 37.981 minutes, which comes out to 44.633017 degrees, instead of 44.633117 as in the pull request.

2022-05-31 16:56 UTC, lstoltz commented
> Verified serial numbers from pre-deployment test files, except for the ctd and velpt. Everything else appears to be in order except for a discrepancy in deployment latitude. The cruise report reports 44 degrees, 37.981 minutes, which comes out to 44.633017 degrees, instead of 44.633117 as in the pull request.

I have the deployment latitude as 44 degrees  37.987 minutes which comes out to 44.633117. I checked the Al Fresco submission and saw the same results. Did I send you an incorrect form by mistake? If so please delete and refer to the correct version documented on Al Fresco. Thanks.

2022-05-31 17:30 UTC, merged